services:
  - type: web
    name: vietxanh-be
    env: node
    region: singapore
    plan: free
    buildCommand: npm ci && npm run build && chmod +x start.sh
    startCommand: bash start.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
